// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: work/sg/admin/v1/api.proto

// package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/bilibili/kratos/tool/protobuf/pkg/extensions/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	v1 "gitlab.duoshengbu.com/be/dsb-server-proto/work/sg/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DsbAdminMessageReq struct {
	// 消息字节数组
	Message *v1.SgMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty" validate:"required"`
	// 用户ID
	UserIdList           []int64  `protobuf:"varint,2,rep,packed,name=user_id_list,json=userIdList,proto3" json:"user_id_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DsbAdminMessageReq) Reset()         { *m = DsbAdminMessageReq{} }
func (m *DsbAdminMessageReq) String() string { return proto.CompactTextString(m) }
func (*DsbAdminMessageReq) ProtoMessage()    {}
func (*DsbAdminMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_13e0fa40c7ea69dc, []int{0}
}
func (m *DsbAdminMessageReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DsbAdminMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DsbAdminMessageReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DsbAdminMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DsbAdminMessageReq.Merge(m, src)
}
func (m *DsbAdminMessageReq) XXX_Size() int {
	return m.Size()
}
func (m *DsbAdminMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DsbAdminMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_DsbAdminMessageReq proto.InternalMessageInfo

type DsbAdminMessageSingleReq struct {
	// 消息字节数组
	Message *v1.SgMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty" validate:"required"`
	// 用户ID
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DsbAdminMessageSingleReq) Reset()         { *m = DsbAdminMessageSingleReq{} }
func (m *DsbAdminMessageSingleReq) String() string { return proto.CompactTextString(m) }
func (*DsbAdminMessageSingleReq) ProtoMessage()    {}
func (*DsbAdminMessageSingleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_13e0fa40c7ea69dc, []int{1}
}
func (m *DsbAdminMessageSingleReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DsbAdminMessageSingleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DsbAdminMessageSingleReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DsbAdminMessageSingleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DsbAdminMessageSingleReq.Merge(m, src)
}
func (m *DsbAdminMessageSingleReq) XXX_Size() int {
	return m.Size()
}
func (m *DsbAdminMessageSingleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DsbAdminMessageSingleReq.DiscardUnknown(m)
}

var xxx_messageInfo_DsbAdminMessageSingleReq proto.InternalMessageInfo

type DsbAdminMessageResp struct {
	// 状态
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	// 发送的终端数
	Clients              int64    `protobuf:"varint,2,opt,name=clients,proto3" json:"clients"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DsbAdminMessageResp) Reset()         { *m = DsbAdminMessageResp{} }
func (m *DsbAdminMessageResp) String() string { return proto.CompactTextString(m) }
func (*DsbAdminMessageResp) ProtoMessage()    {}
func (*DsbAdminMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_13e0fa40c7ea69dc, []int{2}
}
func (m *DsbAdminMessageResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DsbAdminMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DsbAdminMessageResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DsbAdminMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DsbAdminMessageResp.Merge(m, src)
}
func (m *DsbAdminMessageResp) XXX_Size() int {
	return m.Size()
}
func (m *DsbAdminMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DsbAdminMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_DsbAdminMessageResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DsbAdminMessageReq)(nil), "com.sg.admin.service.v1.DsbAdminMessageReq")
	proto.RegisterType((*DsbAdminMessageSingleReq)(nil), "com.sg.admin.service.v1.DsbAdminMessageSingleReq")
	proto.RegisterType((*DsbAdminMessageResp)(nil), "com.sg.admin.service.v1.DsbAdminMessageResp")
}

func init() { proto.RegisterFile("work/sg/admin/v1/api.proto", fileDescriptor_13e0fa40c7ea69dc) }

var fileDescriptor_13e0fa40c7ea69dc = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x9d, 0x04, 0x12, 0x98, 0x78, 0x9a, 0x2a, 0x09, 0xb1, 0x26, 0x61, 0x40, 0x08, 0x68,
	0x67, 0x48, 0xbd, 0xf5, 0xd6, 0xc5, 0x8b, 0x50, 0x11, 0x36, 0x37, 0x2f, 0x75, 0x76, 0x67, 0x18,
	0x07, 0x77, 0x67, 0xb6, 0xfb, 0x66, 0xd7, 0xbb, 0x08, 0xfd, 0x03, 0x3c, 0xf8, 0x2f, 0xf5, 0x28,
	0x78, 0x0f, 0x1a, 0x3c, 0xf5, 0xe8, 0x5f, 0x20, 0xb3, 0x3f, 0x10, 0x5b, 0x04, 0x2f, 0x3d, 0xed,
	0xdb, 0xef, 0x7b, 0xfb, 0xfd, 0x7c, 0xd9, 0xf7, 0xf0, 0xfc, 0x83, 0x2b, 0xdf, 0x73, 0xd0, 0x5c,
	0xc8, 0xdc, 0x58, 0x5e, 0x6f, 0xb8, 0x28, 0x0c, 0x2b, 0x4a, 0xe7, 0x1d, 0x99, 0xa6, 0x2e, 0x67,
	0xa0, 0x59, 0xd3, 0x62, 0xa0, 0xca, 0xda, 0xa4, 0x8a, 0xd5, 0x9b, 0xf9, 0x03, 0xed, 0xb4, 0x6b,
	0x66, 0x78, 0xa8, 0xda, 0xf1, 0xf9, 0xa1, 0x76, 0x4e, 0x67, 0x2a, 0x18, 0x70, 0x61, 0xad, 0xf3,
	0xc2, 0x1b, 0x67, 0xa1, 0xeb, 0x3e, 0xea, 0x41, 0xa9, 0xcb, 0x73, 0xf7, 0x37, 0x89, 0x5e, 0x22,
	0x4c, 0x5e, 0x40, 0x72, 0x1a, 0x40, 0xaf, 0x14, 0x80, 0xd0, 0x2a, 0x56, 0x17, 0xe4, 0x35, 0x1e,
	0xe7, 0xed, 0xdb, 0x0c, 0xad, 0xd0, 0x7a, 0x72, 0x7c, 0xc8, 0x82, 0x4b, 0xc8, 0xd4, 0xba, 0xb0,
	0x7a, 0xc3, 0xb6, 0xba, 0xfb, 0x22, 0x9a, 0xfe, 0xda, 0x2d, 0x0f, 0x6a, 0x91, 0x19, 0x29, 0xbc,
	0x3a, 0xa1, 0xa5, 0xba, 0xa8, 0x4c, 0xa9, 0x24, 0x8d, 0x7b, 0x17, 0xb2, 0xc2, 0xf7, 0x2b, 0x50,
	0xe5, 0xb9, 0x91, 0xe7, 0x99, 0x01, 0x3f, 0x1b, 0xac, 0x86, 0xeb, 0x61, 0x8c, 0x83, 0xf6, 0x52,
	0x9e, 0x19, 0xf0, 0xf4, 0x13, 0xc2, 0xb3, 0x1b, 0x49, 0xb6, 0xc6, 0xea, 0xec, 0x6e, 0xf2, 0x4c,
	0xf1, 0xb8, 0xcb, 0x33, 0x1b, 0xac, 0xd0, 0x7a, 0x18, 0x8f, 0xda, 0x28, 0xf4, 0x2d, 0x3e, 0xb8,
	0xf5, 0x3f, 0xa0, 0x20, 0x14, 0x8f, 0xc0, 0x0b, 0x5f, 0x41, 0xc3, 0x1f, 0x46, 0xf8, 0x7a, 0xb7,
	0xec, 0x94, 0xb8, 0x7b, 0x92, 0x27, 0x78, 0x9c, 0x66, 0x46, 0x59, 0x0f, 0xad, 0x67, 0x34, 0xb9,
	0xde, 0x2d, 0x7b, 0x29, 0xee, 0x8b, 0xe3, 0x2f, 0x08, 0x4f, 0x7a, 0xc4, 0x69, 0x61, 0xc8, 0x25,
	0xc2, 0x93, 0xad, 0xb2, 0xb2, 0xc3, 0x91, 0xa7, 0xec, 0x1f, 0xdb, 0x67, 0xb7, 0x17, 0x35, 0x7f,
	0xf6, 0xff, 0xc3, 0x50, 0xd0, 0xc7, 0x1f, 0xbf, 0xfd, 0xfc, 0x3c, 0x98, 0xd2, 0x87, 0x5c, 0x76,
	0x5d, 0x0e, 0x7f, 0xc8, 0xd1, 0xd9, 0xd5, 0x8f, 0xc5, 0xbd, 0xab, 0xfd, 0x02, 0x7d, 0xdd, 0x2f,
	0xd0, 0xf7, 0xfd, 0x02, 0xbd, 0x39, 0xd1, 0xc6, 0x67, 0x22, 0x61, 0xb2, 0x72, 0xf0, 0x4e, 0x59,
	0x9d, 0x54, 0x81, 0xc7, 0x13, 0x15, 0x0c, 0x8e, 0x02, 0x4d, 0x95, 0x47, 0xed, 0x3d, 0xde, 0x3c,
	0xe7, 0x64, 0xd4, 0xe8, 0xcf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x08, 0x34, 0x80, 0xe9,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DsbAdminApiClient is the client API for DsbAdminApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DsbAdminApiClient interface {
	SendMessage(ctx context.Context, in *DsbAdminMessageReq, opts ...grpc.CallOption) (*DsbAdminMessageResp, error)
}

type dsbAdminApiClient struct {
	cc *grpc.ClientConn
}

func NewDsbAdminApiClient(cc *grpc.ClientConn) DsbAdminApiClient {
	return &dsbAdminApiClient{cc}
}

func (c *dsbAdminApiClient) SendMessage(ctx context.Context, in *DsbAdminMessageReq, opts ...grpc.CallOption) (*DsbAdminMessageResp, error) {
	out := new(DsbAdminMessageResp)
	err := c.cc.Invoke(ctx, "/com.sg.admin.service.v1.DsbAdminApi/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DsbAdminApiServer is the server API for DsbAdminApi service.
type DsbAdminApiServer interface {
	SendMessage(context.Context, *DsbAdminMessageReq) (*DsbAdminMessageResp, error)
}

func RegisterDsbAdminApiServer(s *grpc.Server, srv DsbAdminApiServer) {
	s.RegisterService(&_DsbAdminApi_serviceDesc, srv)
}

func _DsbAdminApi_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DsbAdminMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DsbAdminApiServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.sg.admin.service.v1.DsbAdminApi/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DsbAdminApiServer).SendMessage(ctx, req.(*DsbAdminMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DsbAdminApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.sg.admin.service.v1.DsbAdminApi",
	HandlerType: (*DsbAdminApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _DsbAdminApi_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "work/sg/admin/v1/api.proto",
}

func (m *DsbAdminMessageReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DsbAdminMessageReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Message != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.Message.Size()))
		n1, err := m.Message.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.UserIdList) > 0 {
		dAtA3 := make([]byte, len(m.UserIdList)*10)
		var j2 int
		for _, num1 := range m.UserIdList {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		dAtA[i] = 0x12
		i++
		i = encodeVarintApi(dAtA, i, uint64(j2))
		i += copy(dAtA[i:], dAtA3[:j2])
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DsbAdminMessageSingleReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DsbAdminMessageSingleReq) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Message != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.Message.Size()))
		n4, err := m.Message.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.UserId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.UserId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DsbAdminMessageResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DsbAdminMessageResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.Status))
	}
	if m.Clients != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintApi(dAtA, i, uint64(m.Clients))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintApi(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *DsbAdminMessageReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Message != nil {
		l = m.Message.Size()
		n += 1 + l + sovApi(uint64(l))
	}
	if len(m.UserIdList) > 0 {
		l = 0
		for _, e := range m.UserIdList {
			l += sovApi(uint64(e))
		}
		n += 1 + sovApi(uint64(l)) + l
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DsbAdminMessageSingleReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Message != nil {
		l = m.Message.Size()
		n += 1 + l + sovApi(uint64(l))
	}
	if m.UserId != 0 {
		n += 1 + sovApi(uint64(m.UserId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DsbAdminMessageResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovApi(uint64(m.Status))
	}
	if m.Clients != 0 {
		n += 1 + sovApi(uint64(m.Clients))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovApi(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozApi(x uint64) (n int) {
	return sovApi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *DsbAdminMessageReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DsbAdminMessageReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DsbAdminMessageReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Message == nil {
				m.Message = &v1.SgMessage{}
			}
			if err := m.Message.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowApi
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.UserIdList = append(m.UserIdList, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowApi
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthApi
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthApi
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.UserIdList) == 0 {
					m.UserIdList = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowApi
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.UserIdList = append(m.UserIdList, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field UserIdList", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DsbAdminMessageSingleReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DsbAdminMessageSingleReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DsbAdminMessageSingleReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Message == nil {
				m.Message = &v1.SgMessage{}
			}
			if err := m.Message.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			m.UserId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DsbAdminMessageResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DsbAdminMessageResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DsbAdminMessageResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Clients", wireType)
			}
			m.Clients = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Clients |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApi
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthApi
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowApi
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipApi(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthApi
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthApi = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi   = fmt.Errorf("proto: integer overflow")
)
