// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: work/sg/admin/v1/api.proto

// package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/bilibili/kratos/tool/protobuf/pkg/extensions/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	v1 "github.com/storv/dsb-server-proto/work/sg/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("work/sg/admin/v1/api.proto", fileDescriptor_13e0fa40c7ea69dc) }

var fileDescriptor_13e0fa40c7ea69dc = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x09, 0x03, 0x43, 0xba, 0x45, 0x48, 0x88, 0x14, 0x05, 0xe8, 0x5e, 0x9f, 0x52, 0x9e,
	0xa0, 0xa8, 0x2b, 0x0b, 0xdd, 0xd8, 0x9c, 0xe4, 0x74, 0x58, 0x10, 0x5f, 0xf0, 0x19, 0xb3, 0xf7,
	0x15, 0x78, 0xa9, 0x8e, 0x48, 0xbc, 0x00, 0x44, 0x3c, 0x08, 0x72, 0x52, 0x40, 0x30, 0xb0, 0x59,
	0xfe, 0xff, 0xff, 0xbe, 0xbb, 0x3f, 0xcd, 0x9f, 0xd8, 0xdd, 0x81, 0x10, 0xe8, 0xa6, 0x35, 0x16,
	0x42, 0x09, 0xba, 0x33, 0xaa, 0x73, 0xec, 0x39, 0x3b, 0xaa, 0xb9, 0x55, 0x42, 0x6a, 0x90, 0x94,
	0xa0, 0x0b, 0xa6, 0x46, 0x15, 0xca, 0xfc, 0x90, 0x98, 0x78, 0xf0, 0x40, 0x7c, 0x8d, 0xf6, 0xfc,
	0x84, 0x98, 0xe9, 0x1e, 0xe3, 0x00, 0xd0, 0xd6, 0xb2, 0xd7, 0xde, 0xb0, 0x95, 0x9d, 0x3a, 0xfd,
	0x02, 0xd5, 0xdc, 0xb6, 0xfc, 0x9b, 0xb4, 0xd8, 0x24, 0xe9, 0x64, 0x25, 0xd5, 0x32, 0x82, 0x96,
	0x9d, 0xc9, 0x24, 0x9d, 0xac, 0xd1, 0x36, 0x57, 0x28, 0xa2, 0x09, 0xb3, 0x53, 0x15, 0xc3, 0x71,
	0x95, 0x31, 0xac, 0x42, 0xa9, 0xd6, 0xb4, 0x53, 0xaf, 0xf1, 0x21, 0x3f, 0xfb, 0xdf, 0x20, 0xdd,
	0xec, 0x7c, 0xf3, 0xfa, 0xf1, 0xbc, 0x3f, 0x9d, 0x1d, 0x43, 0x23, 0xd5, 0xfc, 0xfb, 0x58, 0xf9,
	0xa1, 0x5c, 0xae, 0xb6, 0xef, 0xc5, 0xde, 0xb6, 0x2f, 0x92, 0x97, 0xbe, 0x48, 0xde, 0xfa, 0x22,
	0xb9, 0x59, 0x90, 0xf1, 0xb7, 0x8f, 0x55, 0x1c, 0x0a, 0xe2, 0xd9, 0x85, 0x21, 0x1c, 0x8b, 0x40,
	0x37, 0x1f, 0xef, 0xff, 0x5b, 0x5f, 0x75, 0x30, 0xfc, 0x5f, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x46, 0x13, 0xa4, 0xc2, 0x59, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DsbAdminApiClient is the client API for DsbAdminApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DsbAdminApiClient interface {
	SendMessage(ctx context.Context, in *v1.SgMessageReq, opts ...grpc.CallOption) (*v1.SgMessageResp, error)
}

type dsbAdminApiClient struct {
	cc *grpc.ClientConn
}

func NewDsbAdminApiClient(cc *grpc.ClientConn) DsbAdminApiClient {
	return &dsbAdminApiClient{cc}
}

func (c *dsbAdminApiClient) SendMessage(ctx context.Context, in *v1.SgMessageReq, opts ...grpc.CallOption) (*v1.SgMessageResp, error) {
	out := new(v1.SgMessageResp)
	err := c.cc.Invoke(ctx, "/com.sg.admin.service.v1.DsbAdminApi/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DsbAdminApiServer is the server API for DsbAdminApi service.
type DsbAdminApiServer interface {
	SendMessage(context.Context, *v1.SgMessageReq) (*v1.SgMessageResp, error)
}

func RegisterDsbAdminApiServer(s *grpc.Server, srv DsbAdminApiServer) {
	s.RegisterService(&_DsbAdminApi_serviceDesc, srv)
}

func _DsbAdminApi_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.SgMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DsbAdminApiServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.sg.admin.service.v1.DsbAdminApi/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DsbAdminApiServer).SendMessage(ctx, req.(*v1.SgMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DsbAdminApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.sg.admin.service.v1.DsbAdminApi",
	HandlerType: (*DsbAdminApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _DsbAdminApi_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "work/sg/admin/v1/api.proto",
}
