// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: work/sg/server/v1/api.proto

// package 命名使用 {appid}.{version} 的方式, version 形如 v1, v2 ..

package v1

import (
	context "context"
	fmt "fmt"
	_ "github.com/bilibili/kratos/tool/protobuf/pkg/extensions/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	v1 "github.com/storv/dsb-server-proto/work/sg/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("work/sg/server/v1/api.proto", fileDescriptor_df3e0e30dc35b6a3) }

var fileDescriptor_df3e0e30dc35b6a3 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x09, 0x43, 0x87, 0x30, 0x11, 0x7e, 0x86, 0xb4, 0x0a, 0x28, 0x7b, 0x6d, 0x85, 0x3e,
	0x01, 0x94, 0x8e, 0x2c, 0x64, 0x63, 0x73, 0x52, 0x63, 0x2c, 0x1a, 0x5f, 0x93, 0x7b, 0x13, 0xc4,
	0xca, 0x2b, 0xf0, 0x52, 0x1d, 0x91, 0x78, 0x01, 0x88, 0xe0, 0x3d, 0x90, 0xf3, 0x23, 0xca, 0x8f,
	0xd8, 0x6c, 0x7d, 0xf7, 0xf8, 0x9c, 0xe3, 0xeb, 0x8f, 0xef, 0xa1, 0xbc, 0xe5, 0xa8, 0x38, 0xca,
	0xb2, 0x96, 0x25, 0xaf, 0x13, 0x2e, 0xac, 0x66, 0xb6, 0x04, 0x82, 0x60, 0x37, 0x87, 0x82, 0xa1,
	0x62, 0x8e, 0xe9, 0x5c, 0xb2, 0x3a, 0x09, 0xf7, 0x15, 0x28, 0x68, 0x29, 0x77, 0xa7, 0x6e, 0x30,
	0x1c, 0x2b, 0x00, 0xb5, 0x92, 0xbc, 0xbd, 0x65, 0xd5, 0x35, 0x97, 0x85, 0xa5, 0x87, 0x1e, 0x4e,
	0x7a, 0x28, 0xac, 0xe6, 0xc2, 0x18, 0x20, 0x41, 0x1a, 0x0c, 0x0e, 0xd2, 0x21, 0x40, 0x0e, 0x45,
	0x01, 0xe6, 0x5b, 0x80, 0x93, 0x0f, 0xcf, 0x1f, 0x9d, 0x63, 0x76, 0x6a, 0x75, 0x40, 0xfe, 0x4e,
	0x2a, 0xcd, 0xf2, 0x42, 0x22, 0x0a, 0x25, 0x83, 0x23, 0xe6, 0x74, 0x2e, 0x5c, 0xa7, 0x63, 0x75,
	0xc2, 0x52, 0xd5, 0xd3, 0x4b, 0x79, 0x17, 0x1e, 0xff, 0x3f, 0x80, 0x36, 0x8e, 0x1f, 0x5f, 0xde,
	0x9f, 0xb6, 0x27, 0x71, 0xc8, 0x97, 0x98, 0x4d, 0xbf, 0xfa, 0xe3, 0x86, 0x8d, 0xf4, 0xfd, 0x94,
	0x04, 0xcd, 0x57, 0x5a, 0x1a, 0x0a, 0x0e, 0x59, 0x57, 0x85, 0x0d, 0x3d, 0xd9, 0xc2, 0xf5, 0x0c,
	0xe3, 0x3f, 0xbc, 0xe6, 0x50, 0x99, 0x5e, 0xd7, 0xba, 0x8d, 0x5b, 0xb7, 0x83, 0x78, 0xef, 0xa7,
	0x1b, 0x09, 0x3a, 0x5b, 0xac, 0xdf, 0xa2, 0xad, 0x75, 0x13, 0x79, 0xcf, 0x4d, 0xe4, 0xbd, 0x36,
	0x91, 0x77, 0x35, 0x53, 0x9a, 0x6e, 0xaa, 0xcc, 0x3d, 0xc8, 0x91, 0xa0, 0xac, 0x37, 0x64, 0xd3,
	0xee, 0xff, 0x7f, 0x6d, 0x2e, 0x1b, 0xb5, 0x60, 0xf6, 0x19, 0x00, 0x00, 0xff, 0xff, 0x86, 0x33,
	0x98, 0x76, 0xd5, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DsbApiClient is the client API for DsbApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DsbApiClient interface {
	SendMessage(ctx context.Context, in *v1.SgMessageReq, opts ...grpc.CallOption) (*v1.SgMessageResp, error)
	StatClient(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*v1.CountClientResp, error)
}

type dsbApiClient struct {
	cc *grpc.ClientConn
}

func NewDsbApiClient(cc *grpc.ClientConn) DsbApiClient {
	return &dsbApiClient{cc}
}

func (c *dsbApiClient) SendMessage(ctx context.Context, in *v1.SgMessageReq, opts ...grpc.CallOption) (*v1.SgMessageResp, error) {
	out := new(v1.SgMessageResp)
	err := c.cc.Invoke(ctx, "/com.sg.service.v1.DsbApi/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dsbApiClient) StatClient(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*v1.CountClientResp, error) {
	out := new(v1.CountClientResp)
	err := c.cc.Invoke(ctx, "/com.sg.service.v1.DsbApi/StatClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DsbApiServer is the server API for DsbApi service.
type DsbApiServer interface {
	SendMessage(context.Context, *v1.SgMessageReq) (*v1.SgMessageResp, error)
	StatClient(context.Context, *empty.Empty) (*v1.CountClientResp, error)
}

func RegisterDsbApiServer(s *grpc.Server, srv DsbApiServer) {
	s.RegisterService(&_DsbApi_serviceDesc, srv)
}

func _DsbApi_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.SgMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DsbApiServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.sg.service.v1.DsbApi/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DsbApiServer).SendMessage(ctx, req.(*v1.SgMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DsbApi_StatClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DsbApiServer).StatClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.sg.service.v1.DsbApi/StatClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DsbApiServer).StatClient(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DsbApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.sg.service.v1.DsbApi",
	HandlerType: (*DsbApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _DsbApi_SendMessage_Handler,
		},
		{
			MethodName: "StatClient",
			Handler:    _DsbApi_StatClient_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "work/sg/server/v1/api.proto",
}
